Restore docker build pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,11 @@
 variables:
-  PYTHON_LATEST_SUPPORTED_VERSION: '3.11'
+  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
+  PYTHON_LATEST_SUPPORTED_VERSION: "3.11"
   DOCKER_DRIVER: overlay2
+  PIP_ROOT_USER_ACTION: ignore
+  PIP_DISABLE_PIP_VERSION_CHECK: 1
   SAST_EXCLUDED_PATHS: spec,test,tests,tmp,.tox,output,prototype
   DOCS_RUNNER_TAG: single-gpu
-  UV_CACHE_DIR: .uv-cache
-  UV_LINK_MODE: copy
-  UV_IMAGE: ghcr.io/astral-sh/uv
-  BASE_LAYER: bookworm
-  FORCE_COLOR: '1'
 
 workflow:
   # Allows jobs in this workflow to be interrupted:
@@ -38,9 +36,15 @@ default:
   tags:
     - autoscaler
 
-image: $UV_IMAGE:python$PYTHON_LATEST_SUPPORTED_VERSION-$BASE_LAYER
+image: python:$PYTHON_LATEST_SUPPORTED_VERSION
+
+cache:
+  paths:
+    - .cache/pip
+    - venv/
 
 stages:
+  - build
   - test
   - docs
   - release
@@ -86,65 +90,102 @@ stages:
     when: never
   - if: $CI_COMMIT_BRANCH == 'main'
 
-### TEMPLATES ###
+### PYTHON_VERSION PARALLEL MATRIX TEMPLATE ###
 
-.tox:
-  needs: []
-  before_script:
-    - uv pip install uv tox tox-uv --system
-  cache:
-    - key:
-        files:
-          - environment/requirements.txt
-          - environment/requirements-dev.txt
-      paths:
-        - $UV_CACHE_DIR
-        - data
-  after_script:
-    - uv cache prune --ci
-
-.tox_all:
-  extends: .tox
-  image: $UV_IMAGE:python$PYTHON_VERSION-$BASE_LAYER
+.python_version_matrix:
   parallel:
     matrix:
       - PYTHON_VERSION: ["3.9", "3.10", "3.11"]
 
-### TEST ###
+### DOCKER TEMPLATES ###
 
-lint:
-  extends: .tox
-  script:
-    - tox -e lint
-  rules: *on_run
+.docker:
+  image: docker:25.0.5-git
+  before_script:
+    - if [[ ! $(which bash) ]]; then apk add --no-cache bash; fi
 
-minimum install:
-  extends: .tox
-  script:
-    - tox -e deps
-  rules: *on_run
+.harbor:
+  extends: .docker
+  before_script:
+    - if [[ ! $(which bash) ]]; then apk add --no-cache bash; fi
+    - echo ${DATAEVAL_HARBOR_TOKEN} | docker login harbor.jatic.net -u 'robot$dataeval+dataeval-build' --password-stdin || echo "Failed to login to Harbor..."
+  after_script:
+    - docker logout harbor.jatic.net|| echo "Failed to logout from Harbor..."
 
-typecheck:
-  extends: .tox_all
+.build_task:
+  extends: [.harbor, .python_version_matrix]
+  needs: [build]
   script:
-    - tox -e type-py${PYTHON_VERSION:0:1}${PYTHON_VERSION:2}
-  rules: *on_run
-
-test:
-  extends: .tox_all
-  script:
-    - tox -e py${PYTHON_VERSION:0:1}${PYTHON_VERSION:2}
+    - ./build --push ${PYTHON_VERSION} ${TASK}
   artifacts:
-    reports:
-      junit: output/junit.*.xml
     paths:
       - output/*
   rules: *on_run
 
-coverage:
-  needs: [test]
+### BUILD ###
+
+build:
+  stage: build
+  extends: [.harbor, .python_version_matrix]
+  needs: [verify lock]
+  script:
+    - apk add --no-cache parallel
+    - ./build --build-only --push ${PYTHON_VERSION}
+  rules: *on_run
+
+verify lock:
+  stage: build
   before_script:
-    - uv pip install coverage --system
+    - pip install tox
+  script:
+    - tox -e check
+  rules: *on_run
+
+docker info:
+  stage: build
+  extends: .docker
+  script:
+    - echo ===========================================================
+    - |
+      docker info
+      echo ===========================================================
+    - |
+      docker version
+      echo ===========================================================
+    - |
+      docker buildx ls
+      echo ===========================================================
+  rules: *on_run
+
+### TEST ###
+
+linting:
+  extends: .build_task
+  variables:
+    TASK: lint
+
+dependency tests:
+  extends: .build_task
+  variables:
+    TASK: deps
+
+tests:
+  extends: .build_task
+  variables:
+    TASK: unit
+  artifacts:
+    reports:
+      junit: output/junit.*.xml
+
+type checks:
+  extends: .build_task
+  variables:
+    TASK: type
+
+coverage:
+  needs: [tests]
+  before_script:
+    - pip install coverage
   script:
     # TODO: Move coverage report generation in to build script (and/or resolve issue with using symlinks instead of a full recursive copy)
     - cp --recursive $(pwd) /dataeval
@@ -163,28 +204,24 @@ coverage:
       - htmlcov/
   rules: *on_run
 
-verify lock:
-  extends: .tox
-  script:
-    - tox -e check
-  rules: *on_run
-
 ### DOCS ###
 
 doctest:
   stage: docs
-  extends: .tox
+  extends: .harbor
+  needs: [build]
   script:
-    - tox -e doctest
+    - ./build --push doctest
   rules: *on_run
 
 docs:
   stage: docs
-  extends: .tox
+  extends: .harbor
+  needs: [verify lock]
   tags:
     - $DOCS_RUNNER_TAG
   script:
-    - tox -e $TASK
+    - ./build --push $TASK --gpu
   artifacts:
     paths:
       - output/docs/.jupyter_cache/
@@ -230,7 +267,7 @@ pages:
 update merge request:
   stage: release
   before_script:
-    - uv pip install requests --system
+    - pip install requests
   script:
     - .gitlab/scripts/update_merge_request.py $CI_MERGE_REQUEST_IID $CI_PIPELINE_ID
   rules: *on_merge_request_only
@@ -240,7 +277,7 @@ update merge request:
 tag release candidate:
   stage: release
   before_script:
-    - uv pip install requests --system
+    - pip install requests
   script:
     - .gitlab/scripts/update_latest_known_good.py
   rules: *on_commit_main_only
@@ -251,7 +288,7 @@ remove image tags:
   stage: release
   needs: []
   before_script:
-    - uv pip install requests --system
+    - pip install requests
   script:
     - .gitlab/scripts/remove_image_tags.py
   rules: *on_commit_main_only
@@ -263,7 +300,7 @@ create release:
   stage: release
   needs: []
   before_script:
-    - uv pip install requests --system
+    - pip install requests
   script:
     - .gitlab/scripts/create_release.py
   rules: *on_release
